"use strict";
exports.__esModule = true;
var TYPES = {
  FETCH_STATE: "FETCH_STATE",
  SET_STATE: "SET_STATE",
  SORT_BY_TITLES: "SORT_BY_TITLES",
  SORT_BY_AUTHORS: "SORT_BY_AUTHORS",
  FILTER_BY_LARGE_MANUSCRIPTS: "FILTER_BY_LARGE_MANUSCRIPTS",
  FILTER_BY_SMALL_MANUSCRIPTS: "FILTER_BY_SMALL_MANUSCRIPTS",
  RESET_STATE: "RESET_STATE",
};
exports["default"] = TYPES;
