import { TypesConfig } from "../configs";

const TYPES: TypesConfig = {
  FETCH_STATE: "FETCH_STATE",
  SET_STATE: "SET_STATE",
  SORT_BY_TITLES: "SORT_BY_TITLES",
  SORT_BY_AUTHORS: "SORT_BY_AUTHORS",
  SORT_BY_TYPES: "SORT_BY_TYPES",
  FILTER_BY_LARGE_MANUSCRIPTS: "FILTER_BY_LARGE_MANUSCRIPTS",
  FILTER_BY_SMALL_MANUSCRIPTS: "FILTER_BY_SMALL_MANUSCRIPTS",
  RESET_STATE: "RESET_STATE",
};

export default TYPES;
