import { TypesConfig } from "../configs";

const TYPES: TypesConfig = {
  FETCH_STATE: "FETCH_STATE",
  SET_STATE: "SET_STATE",
  SORT_MANUSCRIPTS: "SORT_MANUSCRIPTS",
  FILTER_MANUSCRIPTS: "FILTER_MANUSCRIPTS",
  SEARCH_MANUSCRIPTS: "SEARCH_MANUSCRIPTS",
  RESET_STATE: "RESET_STATE",
};

export default TYPES;
