import { TypesConfig } from "../configs";

const TYPES: TypesConfig = {
  FETCH_STATE: "FETCH_STATE",
  SET_STATE: "SET_STATE",
  SORT_STATE: "SORT_STATE",
  FILTER_BY_LARGE_MANUSCRIPTS: "FILTER_BY_LARGE_MANUSCRIPTS",
  FILTER_BY_SMALL_MANUSCRIPTS: "FILTER_BY_SMALL_MANUSCRIPTS",
  RESET_STATE: "RESET_STATE",
};

export default TYPES;
