import { TypesConfig } from '../configs';

const TYPES: TypesConfig = {
  READ_ALL_MANUSCRIPTS: 'READ_ALL_MANUSCRIPTS',
  DELETE_MANUSCRIPT: 'DELETE_MANUSCRIPT',
  CREATE_MANUSCRIPT: 'CREATE_MANUSCRIPT',
  SET_REGISTRATION: 'SET_REGISTRATION',
  SET_AUTHENTICATION: 'SET_AUTHENTICATION',
  UPDATE_ALL_MANUSCRIPTS: 'UPDATE_ALL_MANUSCRIPTS',
  CHECK_INTERSECTIONS: 'CHECK_INTERSECTIONS',
  SORT_MANUSCRIPTS: 'SORT_MANUSCRIPTS',
  FILTER_MANUSCRIPTS: 'FILTER_MANUSCRIPTS',
  SEARCH_MANUSCRIPTS: 'SEARCH_MANUSCRIPTS',
  RESET_STATE: 'RESET_STATE',
};

export default TYPES;
